### ISSUE TITLE
Packaging 26.2 breaks DependencyVersion deepcopy and dependency resolution

### ISSUE THREAD

**Issue by ianpittwood** [posit-dev/images-shared#721]
## Summary

`just posit-bakery/test` fails broadly after upgrading `packaging` from 25.0 to 26.2. The failures all originate from `DependencyVersion` losing its subclass attributes during `copy.deepcopy()`.

## Reproduction

On commit `3e0391c0`:

```text
cd posit-bakery
just test
```

Result: 71 failed, 1984 passed.

A minimal reproduction is:

```python
import copy
from posit_bakery.config.dependencies.version import DependencyVersion

version = copy.deepcopy(DependencyVersion("3.13.7"))
print(version.minor)
```

With `packaging==26.2`, this raises:

```text
AttributeError: 'DependencyVersion' object has no attribute '_has_minor'
```

The same reproduction works with `packaging==25.0`.

## Cause

`DependencyVersion` subclasses `packaging.version.Version` and adds `_has_minor`, `_has_micro`, and `_original`. The dependency providers intentionally deep-copy cached versions in:

- `posit_bakery/config/dependencies/python.py`
- `posit_bakery/config/dependencies/r.py`
- `posit_bakery/config/dependencies/quarto.py`
- `posit_bakery/config/dependencies/positron.py`

Packaging 26.2 changed `Version` to a slotted/stable-pickle implementation. Its copy/deepcopy state does not preserve these subclass attributes, so dependency resolution fails when accessing `v.minor`.

The triggering change in this branch is the dependency update in commit `3e0391c0`, which changed:

```diff
- packaging>=25.0,<26.0
+ packaging>=25.0,<27.0
```

and locked `packaging` to 26.2.

## Expected behavior

Dependency versions should remain usable after the documented defensive deep-copy operation, and the test suite should pass with the supported packaging range.

## Possible fixes

Either restore the `<26.0` upper bound temporarily, or update `DependencyVersion`/the caching strategy so its subclass state survives copying while retaining compatibility with packaging 26.x.
